version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "foreman start"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "8080:8080"
    depends_on:
      - db
